### ISSUE TITLE
Withdraw Vesting Routes "to_account" not found in  api/v1/accounts/{username}/

### ISSUE THREAD

**Issue by nawab69** [emre/tower#13]
Hi I am @nawab69.

I have recently started using tower Api in my steemtools project. When I want to use "/api/v1/accounts" end point I found an issue.

### Issue
- There is no "to_account" string in this api.  On steemjs ' get_withdraw_routes 'Api endpoint there is a JSON strings to find the current withdraw routes of an account. But in tower api there is no such a string/object to find any accounts current withdraw vesting route and percentage.

I think that should be included in tower api.

**Comment by emre** [comment]
Investigated the issue, looks like Hivemind doesn't store that info, therefore tower can't answer that.
